# Generated by Django 2.2.3 on 2019-10-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
