# Generated by Django 2.2.3 on 2019-10-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_apps_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
